package main

func main(){
    //抛出错误 结束之后的操作
    panic("some error happen, this is output info")
}
